version: "3"

services:
  minecraft-monga-vanila:
    image: lorthe/monga-minecraft
    container_name: minecraft-monga-vanila
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      # attach a directory relative to the directory containing this compose file
      - ~/server-data/minecraft/monga-vanila:/data


#docker compose -f "minecraft/monga-vanila/docker-compose.yml" up -d --build


