version: "3"

services:
  mc:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      # attach a directory relative to the directory containing this compose file

    volumes:
      - ~/data/minecraft/monga-vanila/:/data


#docker compose -f "minecraft/monga-vanila/docker-compose.yml" up -d --build


