# docker-compose.yml
version: "3"
services:
  minecraft-survival:
    image: lorthe/monga-minecraft
    container_name: mc-monga
    restart: unless-stopped

    env_file:
      - .env

    ports:
      - 25565:25565

    tty: true
    stdin_open: true

    volumes:
      # Server data
      - ./data/:/data

