# docker-compose.yml
version: "3"
services:
  minecraft-survival:
    image: lorthe/monga-minecraft
    restart: unless-stopped
    
    env_file:
      - .env

    ports:
      - 25565:25565

    tty: true
    stdin_open: true

    volumes:
      # Server data
      - ./data/monga-vanila/:/data

#docker-compose -f docker-compose.yml up -d --build
#docker-compose -f "minecraft/monga-vanila/docker-compose.yml" up -d --build


