version: '3.3'

services:
  web:
    image: itzg/rcon
    environment:
      RWA_USERNAME: monga
      RWA_ADMIN: "TRUE"
      RWA_RCON_HOST: "mc-monga"
      RWA_RCON_PASSWORD: "demo"
    env_file:
      - .env
    ports:
      - 4326:4326
      - 4327:4327
      
  minecraft-survival:
    image: lorthe/monga-minecraft
    container_name: mc-monga
    restart: unless-stopped
    
    environment:
      EULA: "TRUE"
      RCON_PASSWORD: "demo"
    env_file:
      - .env
    ports:
      - 25565:25565

    tty: true
    stdin_open: true

    volumes:
      # Server data
      - ./data/:/data
